export const TASKS_TYPE = {
  GET_ALL_TASKS: "GET_ALL_TASKS",
  ADD_NEW_TASK: "ADD_NEW_TASK",
  GET_TASK_BY_ID: "GET_TASK_BY_ID",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE"
};
