import { TASK_STATUS } from "../../constants";

export const initArray = [
  {
    id: 1,
    title: "Task 1",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.NEW,
  },
  {
    id: 2,
    title: "Task 2",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.DOING,
  },
  {
    id: 3,
    title: "Task 3",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.DONE,
  },
  {
    id: 4,
    title: "Task 4",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.DONE,
  },
  {
    id: 5,
    title: "Task 5",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.DOING,
  },
  {
    id: 6,
    title: "Task 6",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.NEW,
  },
  {
    id: 7,
    title: "Task 7",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.NEW,
  },
  {
    id: 8,
    title: "Task 8",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.DOING,
  },
  {
    id: 9,
    title: "Task 9",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.NEW,
  },
  {
    id: 10,
    title: "Task 10",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.NEW,
  },
  {
    id: 11,
    title: "Task 11",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.DONE,
  },
  {
    id: 12,
    title: "Task 12",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.NEW,
  },
  {
    id: 13,
    title: "Task 13",
    creator: "Huy",
    createAt: "123",
    description: "ABCXYZ",
    status: TASK_STATUS.NEW,
  },
];
